language: csharp
notifications:
  webhooks: https://tomacheese.com/tomachi/travisci_notice_book000.php
mono: none
solution: Memorization.sln
dotnet: 2.1.6
install:
- dotnet restore

script:
 - dotnet build -c Release
 - dotnet test Memorization/Memorization.csproj